version: '3'

volumes:
  exist-data:
  exist-config:
  wordpress-mysql:
  wordpress-uploads:
  redis-data:
  api-storage-framework:
  api-storage-logs:
  api-public-facsimile:
  api-mysql:
  frontend-dist:

services:
  # XML database
  exist:
    image: existdb/existdb:5.2.0
    restart: unless-stopped
    volumes:
      - exist-data:/exist/data/
      - exist-config:/exist/etc/

  # Wordpress database
  wordpress-mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - wordpress-mysql:/var/lib/mysql

  # Wordpress php
  wordpress:
    image: famileengelsbriefe/wordpress:latest
    restart: unless-stopped
    depends_on:
      - wordpress-mysql
    volumes:
      - ./wordpress:/wordpress
      - ./docker/php/upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - wordpress-uploads:/wordpress/wp-content/uploads

  # API database
  api-mysql:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - api-mysql:/var/lib/mysql

  # Engels API
  api:
    image: famileengelsbriefe/api:latest
    restart: unless-stopped
    volumes:
      - api-storage-framework:/api/storage/framework
      - api-storage-logs:/api/storage/logs
      - api-public-facsimile:/api/public/facsimile
    depends_on:
      - exist
      - api-mysql
      - redis

  # Engels API queue worker
  api-horizon:
    image: famileengelsbriefe/api:latest
    restart: unless-stopped
    entrypoint: php /api/artisan horizon
    volumes:
      - api-storage-framework:/api/storage/framework
      - api-storage-logs:/api/storage/logs
      - api-public-facsimile:/api/public/facsimile
    depends_on:
      - exist
      - api-mysql
      - redis

  # Caching server
  redis:
    image: redis:6.0
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  # Build production ready frontend
  frontend:
    image: famileengelsbriefe/frontend:latest
    restart: "no"
    volumes:
      - frontend-dist:/dist

  # Webserver proxy
  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - wordpress
      - api
    volumes:
      -  ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./wordpress:/wordpress:ro
      - wordpress-uploads:/wordpress/wp-content/uploads:ro
      - ./api/public:/api/public:ro
      - frontend-dist:/frontend:ro
