name: 'Publish storybook to chromatic'

on: [push]

jobs:
  chromatic:
    runs-on: ubuntu-20.04

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$FONTAWESOME_AUTH_TOKEN" > .npmrc'
        shell: bash
        env:
          FONTAWESOME_AUTH_TOKEN: ${{ secrets.FONTAWESOME_AUTH_TOKEN }}
      - run: yarn install
      - run: |
          yarn build-storybook
          CHROMATIC_PROJECT_TOKEN=${{ secrets.CHROMATIC_PROJECT_TOKEN }} npx chromatic --exit-zero-on-changes -d storybook-static/
