name: 'Deploy on engels server'

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: /home/debian/docker/update_webapp.sh
        command_timeout: '20m'
